influxdb:
  image: influxdb:1.4.2
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - ./influxDbData:/var/lib/influxdb

timeshift:
  tty: true
  stdin_open: true
  image: thedrhax/influxdb-timeshift-proxy:1.0
  container_name: timeshift
  ports:
    - "8089:8089"
  env_file:
    - 'env.timeshift'
  links:
    - influxdb

grafana:
  image: grafana/grafana:4.2.0
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    - ./dashboards:/usr/share/grafana/public/dashboards

#jmxtrans:
#  image: jmxtrans/jmxtrans:latest
#  depends_on:
#    - influxdb
#  links:
#    - influxdb
#    - grafana
#  environment:
#    - JMX_HOST_TEST=192.168.1.235
##    - JMX_HOST_TEST=docker.for.mac.localhost
#    - JMX_PORT_TEST=9998
#    - JMX_ALIAS_TEST=TEST
#    - INFLUXDB_USER=root
#    - INFLUXDB_PASSWORD=root
#    - INFLUXDB_NAME=influx
#    - INFLUXDB_URL=http://influxdb:8086
#  volumes:
#    - ./config/types.db:/usr/share/collectd/types.db:ro
#    - ./config/localtime:/etc/localtime:ro
#    - ./config/timezone:/etc/timezone:ro
#    - ./config/influxdb.json.tmpl:/var/lib/jmxtrans/influxdb.json.tmpl
#    - ./config/grafanadashboard.json.tmpl:/dashboards/grafanadashboard.json.tmpl
#    - ./config/docker-entrypoint.sh:/docker-entrypoint.sh
